-- ALTER TABLE "inventory"."product_prices" RENAME COLUMN "purchase_tax" TO "currency_code";--> statement-breakpoint
-- ALTER TABLE "core"."exchange_rates" DROP CONSTRAINT "exchange_rates_tenant_id_tenants_id_fk";
-- --> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ALTER COLUMN "base_cost" SET DEFAULT '0';--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ALTER COLUMN "base_cost" SET NOT NULL;--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ALTER COLUMN "other_costs" SET DEFAULT '0';--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ALTER COLUMN "other_costs" SET NOT NULL;--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ALTER COLUMN "total_cost" SET DEFAULT '0';--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ALTER COLUMN "total_cost" SET NOT NULL;--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ALTER COLUMN "expense_percent" SET DEFAULT '0';--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ALTER COLUMN "expense_percent" SET NOT NULL;--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ALTER COLUMN "profit_percent" SET DEFAULT '0';--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ALTER COLUMN "profit_percent" SET NOT NULL;--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ALTER COLUMN "sales_tax_percent" SET DEFAULT '16.00';--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ALTER COLUMN "sales_tax_percent" SET NOT NULL;--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ADD COLUMN "purchase_exchange_rate" numeric(18, 6) DEFAULT '1.000000' NOT NULL;--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ADD COLUMN "sales_exchange_rate" numeric(18, 6) DEFAULT '1.000000' NOT NULL;--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ADD COLUMN "purchase_tax_percent" numeric(5, 2) DEFAULT '16.00' NOT NULL;--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ADD COLUMN "base_cost_ves" numeric(18, 6) DEFAULT '0' NOT NULL;--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ADD COLUMN "other_costs_ves" numeric(18, 6) DEFAULT '0' NOT NULL;--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ADD COLUMN "total_cost_ves" numeric(18, 6) DEFAULT '0' NOT NULL;--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ADD COLUMN "sale_price" numeric(18, 6);--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ADD COLUMN "offer_sale_price" numeric(18, 6);--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ADD COLUMN "bs_price_amount" numeric(18, 6);--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ADD COLUMN "final_price_net" numeric(18, 6) DEFAULT '0' NOT NULL;--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ADD COLUMN "final_price_gross" numeric(18, 6) DEFAULT '0' NOT NULL;--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ADD COLUMN "final_price_net_ves" numeric(18, 6) DEFAULT '0' NOT NULL;--> statement-breakpoint
-- ALTER TABLE "inventory"."product_prices" ADD COLUMN "final_price_gross_ves" numeric(18, 6) DEFAULT '0' NOT NULL;--> statement-breakpoint
-- ALTER TABLE "core"."exchange_rates" DROP COLUMN "tenant_id";