export const banks = [
  { code: '0001', name: 'Banco Central de Venezuela', isActive: true },
  { code: '0102', name: 'Banco de Venezuela, S.A. Banco Universal', isActive: true },
  {
    code: '0104',
    name: 'Banco Venezolano de Crédito, S.A. Banco Universal',
    isActive: true,
  },
  { code: '0105', name: 'Banco Mercantil C.A., Banco Universal', isActive: true },
  { code: '0108', name: 'Banco Provincial, S.A. Banco Universal', isActive: true },
  { code: '0114', name: 'Banco del Caribe C.A., Banco Universal', isActive: true },
  { code: '0115', name: 'Banco Exterior C.A., Banco Universal', isActive: true },
  { code: '0128', name: 'Banco Caroní C.A., Banco Universal', isActive: true },
  { code: '0134', name: 'Banesco Banco Universal, C.A.', isActive: true },
  { code: '0137', name: 'Banco Sofitasa Banco Universal, C.A.', isActive: true },
  { code: '0138', name: 'Banco Plaza, Banco Universal', isActive: true },
  { code: '0146', name: 'Banco de la Gente Emprendedora C.A. (Bangente)', isActive: true },
  { code: '0151', name: 'Banco Fondo Común, C.A Banco Universal', isActive: true },
  { code: '0156', name: '100% Banco, Banco Comercial, C.A', isActive: true },
  { code: '0157', name: 'DelSur, Banco Universal C.A.', isActive: true },
  { code: '0163', name: 'Banco del Tesoro C.A., Banco Universal', isActive: true },
  { code: '0168', name: 'Bancrecer S.A., Banco Microfinanciero', isActive: true },
  { code: '0169', name: 'R4, Banco Microfinanciero, C.A.', isActive: true },
  { code: '0171', name: 'Banco Activo C.A., Banco Universal', isActive: true },
  { code: '0172', name: 'Bancamiga Banco Universal, C.A.', isActive: true },
  { code: '0174', name: 'Banplus Banco Universal, C.A.', isActive: true },
  {
    code: '0175',
    name: 'Banco Digítal de los Trabajadores, Banco Universal',
    isActive: true,
  },
  {
    code: '0177',
    name: 'Banco de la Fuerza Armada Nacional Bolivariana, Banco Universal',
    isActive: true,
  },
  { code: '0191', name: 'Banco Nacional de Crédito C.A., Banco Universal', isActive: true },
  { code: '0601', name: 'Instituto Municipal de Crédito Popular', isActive: true },
];
