export const DEFAULT_PERMISSIONS = [
  // ==========================================
  // MODULO: IAM (Identity & Access Management)
  // ==========================================
  {
    resource: 'iam:users',
    action: 'create',
    name: 'Crear Usuarios',
    description: 'Registrar nuevos usuarios en el tenant.',
    scope: 'tenant',
  },
  {
    resource: 'iam:users',
    action: 'read',
    name: 'Consultar Usuarios',
    description: 'Ver lista de usuarios y perfiles.',
    scope: 'tenant',
  },
  {
    resource: 'iam:users',
    action: 'update',
    name: 'Editar Usuarios',
    description: 'Modificar datos y estado de usuarios.',
    scope: 'tenant',
  },
  {
    resource: 'iam:users',
    action: 'delete',
    name: 'Eliminar Usuarios',
    description: 'Eliminar usuarios del tenant.',
    scope: 'tenant',
  },
  {
    resource: 'iam:roles',
    action: 'create',
    name: 'Crear Roles',
    description: 'Diseñar nuevos roles personalizados.',
    scope: 'tenant',
  },
  {
    resource: 'iam:roles',
    action: 'read',
    name: 'Consultar Roles',
    description: 'Ver roles y sus permisos asignados.',
    scope: 'tenant',
  },
  {
    resource: 'iam:roles',
    action: 'update',
    name: 'Editar Roles',
    description: 'Modificar roles y asignación de permisos.',
    scope: 'tenant',
  },
  {
    resource: 'iam:roles',
    action: 'delete',
    name: 'Eliminar Roles',
    description: 'Eliminar roles del tenant.',
    scope: 'tenant',
  },
  {
    resource: 'iam:permissions',
    action: 'read',
    name: 'Consultar Permisos',
    description: 'Ver catálogo de permisos del sistema.',
    scope: 'tenant',
  },
  {
    resource: 'iam:sessions',
    action: 'read',
    name: 'Consultar Sesiones',
    description: 'Ver sesiones activas de usuarios.',
    scope: 'tenant',
  },
  {
    resource: 'iam:sessions',
    action: 'delete',
    name: 'Revocar Sesiones',
    description: 'Forzar cierre de sesión de usuarios.',
    scope: 'global',
  },

  // ==========================================
  // MODULO: SYSTEM (Configuracion Global)
  // ==========================================
  {
    resource: 'system:tenants',
    action: 'read',
    name: 'Consultar Tenants',
    description: 'Ver organizaciones registradas (SuperAdmin).',
    scope: 'global',
  },
  {
    resource: 'system:tenants',
    action: 'create',
    name: 'Crear Tenants',
    description: 'Registrar nuevas organizaciones (SuperAdmin).',
    scope: 'global',
  },
  {
    resource: 'system:tenants',
    action: 'update',
    name: 'Editar Tenants',
    description: 'Modificar datos de organizaciones (SuperAdmin).',
    scope: 'global',
  },
  {
    resource: 'system:tenants',
    action: 'delete',
    name: 'Desactivar Tenants',
    description: 'Desactivar organizaciones (SuperAdmin).',
    scope: 'global',
  },
  {
    resource: 'system:tenants-systems',
    action: 'read',
    name: 'Consultar Config. Empresa',
    description: 'Ver parámetros generales del tenant.',
    scope: 'tenant',
  },
  {
    resource: 'system:tenants-systems',
    action: 'update',
    name: 'Editar Config. Empresa',
    description: 'Modificar parámetros base del tenant.',
    scope: 'tenant',
  },
  {
    resource: 'system:global',
    action: 'read',
    name: 'Consultar Config. Global',
    description: 'Ver configuraciones globales del sistema.',
    scope: 'global',
  },
  {
    resource: 'system:global',
    action: 'update',
    name: 'Editar Config. Global',
    description: 'Modificar configuraciones globales.',
    scope: 'global',
  },
  {
    resource: 'system:currencies',
    action: 'read',
    name: 'Consultar Monedas',
    description: 'Ver monedas disponibles en el sistema.',
    scope: 'global',
  },
  {
    resource: 'system:modules',
    action: 'read',
    name: 'Consultar Módulos',
    description: 'Ver parámetros de módulos del tenant.',
    scope: 'tenant',
  },
  {
    resource: 'system:modules',
    action: 'update',
    name: 'Editar Módulos',
    description: 'Actualizar parámetros de módulos.',
    scope: 'tenant',
  },

  // ==========================================
  // MODULO: SAVINGS (Caja de Ahorro)
  // ==========================================
  {
    resource: 'savings:members',
    action: 'create',
    name: 'Registrar Asociado',
    description: 'Dar de alta un nuevo asociado.',
    scope: 'tenant',
  },
  {
    resource: 'savings:members',
    action: 'read',
    name: 'Consultar Asociados',
    description: 'Ver expediente y datos del asociado.',
    scope: 'tenant',
  },
  {
    resource: 'savings:members',
    action: 'update',
    name: 'Editar Asociado',
    description: 'Modificar datos del asociado.',
    scope: 'tenant',
  },
  {
    resource: 'savings:members',
    action: 'delete',
    name: 'Desactivar Asociado',
    description: 'Desactivar asociado del sistema.',
    scope: 'tenant',
  },
  {
    resource: 'savings:contributions',
    action: 'create',
    name: 'Carga Manual de Haberes',
    description: 'Registrar aportes y retenciones manualmente.',
    scope: 'tenant',
  },
  {
    resource: 'savings:contributions',
    action: 'read',
    name: 'Consultar Haberes',
    description: 'Ver aportes y retenciones.',
    scope: 'tenant',
  },
  {
    resource: 'savings:contributions',
    action: 'update',
    name: 'Editar Haberes',
    description: 'Modificar aportes y retenciones.',
    scope: 'tenant',
  },
  {
    resource: 'savings:contributions',
    action: 'mass_upload',
    name: 'Carga Masiva de Haberes',
    description: 'Subir Excel/CSV de aportes por nómina.',
    scope: 'tenant',
  },
  {
    resource: 'savings:contributions',
    action: 'mass_disburse',
    name: 'Desembolso Masivo de Haberes',
    description: 'Procesar pago masivo de haberes.',
    scope: 'tenant',
  },
  {
    resource: 'savings:withdrawals',
    action: 'create',
    name: 'Solicitar Retiro',
    description: 'Registrar solicitud de retiro de haberes.',
    scope: 'tenant',
  },
  {
    resource: 'savings:withdrawals',
    action: 'read',
    name: 'Consultar Retiros',
    description: 'Ver solicitudes de retiro.',
    scope: 'tenant',
  },
  {
    resource: 'savings:withdrawals',
    action: 'update',
    name: 'Editar Retiro',
    description: 'Modificar solicitud de retiro.',
    scope: 'tenant',
  },
  {
    resource: 'savings:withdrawals',
    action: 'approve',
    name: 'Aprobar Retiros',
    description: 'Aprobar solicitudes de retiro.',
    scope: 'tenant',
  },
  {
    resource: 'savings:withdrawals',
    action: 'reject',
    name: 'Rechazar Retiros',
    description: 'Rechazar solicitudes de retiro.',
    scope: 'tenant',
  },
  {
    resource: 'savings:withdrawals',
    action: 'disburse',
    name: 'Desembolsar Retiro',
    description: 'Ejecutar pago del retiro aprobado.',
    scope: 'tenant',
  },
  {
    resource: 'savings:withdrawal-types',
    action: 'create',
    name: 'Crear Tipo de Retiro',
    description: 'Configurar tipos de retiro.',
    scope: 'tenant',
  },
  {
    resource: 'savings:withdrawal-types',
    action: 'read',
    name: 'Consultar Tipos de Retiro',
    description: 'Ver tipos de retiro configurados.',
    scope: 'tenant',
  },
  {
    resource: 'savings:withdrawal-types',
    action: 'update',
    name: 'Editar Tipo de Retiro',
    description: 'Modificar configuración de tipo de retiro.',
    scope: 'tenant',
  },
  {
    resource: 'savings:withdrawal-types',
    action: 'delete',
    name: 'Eliminar Tipo de Retiro',
    description: 'Eliminar tipo de retiro.',
    scope: 'tenant',
  },
  {
    resource: 'savings:liquidations',
    action: 'create',
    name: 'Iniciar Liquidación',
    description: 'Registrar solicitud de liquidación.',
    scope: 'tenant',
  },
  {
    resource: 'savings:liquidations',
    action: 'read',
    name: 'Consultar Liquidaciones',
    description: 'Ver expedientes de liquidación.',
    scope: 'tenant',
  },
  {
    resource: 'savings:liquidations',
    action: 'update',
    name: 'Editar Liquidación',
    description: 'Modificar datos de liquidación.',
    scope: 'tenant',
  },
  {
    resource: 'savings:liquidations',
    action: 'approve',
    name: 'Aprobar Liquidación',
    description: 'Aprobar solicitud de liquidación.',
    scope: 'tenant',
  },
  {
    resource: 'savings:liquidations',
    action: 'reject',
    name: 'Rechazar Liquidación',
    description: 'Rechazar solicitud de liquidación.',
    scope: 'tenant',
  },
  {
    resource: 'savings:liquidations',
    action: 'process',
    name: 'Calcular Liquidación',
    description: 'Calcular haberes definitivos del asociado.',
    scope: 'tenant',
  },
  {
    resource: 'savings:liquidations',
    action: 'disburse',
    name: 'Desembolsar Liquidación',
    description: 'Ejecutar pago de liquidación.',
    scope: 'tenant',
  },

  // ==========================================
  // MODULO: PORTFOLIO (Préstamos y Créditos)
  // ==========================================
  {
    resource: 'portfolio:loans',
    action: 'create',
    name: 'Solicitar Préstamo',
    description: 'Registrar nueva solicitud de préstamo.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:loans',
    action: 'read',
    name: 'Consultar Préstamos',
    description: 'Ver solicitudes y préstamos activos.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:loans',
    action: 'update',
    name: 'Editar Préstamo',
    description: 'Modificar datos de la solicitud.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:loans',
    action: 'approve',
    name: 'Aprobar Préstamo',
    description: 'Evaluar y aprobar solicitud.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:loans',
    action: 'reject',
    name: 'Rechazar Préstamo',
    description: 'Rechazar solicitud de préstamo.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:loans',
    action: 'disburse',
    name: 'Desembolsar Préstamo',
    description: 'Liberar fondos del préstamo aprobado.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:loans',
    action: 'process',
    name: 'Procesar Préstamo',
    description: 'Ejecutar cálculos y contabilidad del préstamo.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:loans-types',
    action: 'create',
    name: 'Crear Tipo de Préstamo',
    description: 'Configurar tipo de préstamo.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:loans-types',
    action: 'read',
    name: 'Consultar Tipos de Préstamo',
    description: 'Ver tipos de préstamo configurados.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:loans-types',
    action: 'update',
    name: 'Editar Tipo de Préstamo',
    description: 'Modificar configuración de tipo de préstamo.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:loans-types',
    action: 'delete',
    name: 'Eliminar Tipo de Préstamo',
    description: 'Eliminar tipo de préstamo.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:credits',
    action: 'create',
    name: 'Solicitar Crédito',
    description: 'Registrar nueva solicitud de crédito comercial.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:credits',
    action: 'read',
    name: 'Consultar Créditos',
    description: 'Ver solicitudes y créditos activos.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:credits',
    action: 'update',
    name: 'Editar Crédito',
    description: 'Modificar datos de la solicitud.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:credits',
    action: 'approve',
    name: 'Aprobar Crédito',
    description: 'Evaluar y aprobar solicitud de crédito.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:credits',
    action: 'reject',
    name: 'Rechazar Crédito',
    description: 'Rechazar solicitud de crédito.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:credits',
    action: 'disburse',
    name: 'Desembolsar Crédito',
    description: 'Liberar fondos del crédito aprobado.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:credits',
    action: 'process',
    name: 'Procesar Crédito',
    description: 'Ejecutar cálculos y contabilidad del crédito.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:credits-types',
    action: 'create',
    name: 'Crear Tipo de Crédito',
    description: 'Configurar tipo de crédito comercial.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:credits-types',
    action: 'read',
    name: 'Consultar Tipos de Crédito',
    description: 'Ver tipos de crédito configurados.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:credits-types',
    action: 'update',
    name: 'Editar Tipo de Crédito',
    description: 'Modificar tipo de crédito.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:credits-types',
    action: 'delete',
    name: 'Eliminar Tipo de Crédito',
    description: 'Eliminar tipo de crédito.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:payments-loans',
    action: 'create',
    name: 'Registrar Pago de Préstamo',
    description: 'Cargar pago/abono a cuota de préstamo.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:payments-loans',
    action: 'read',
    name: 'Consultar Pagos de Préstamo',
    description: 'Ver historial de pagos de préstamos.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:payments-loans',
    action: 'approve',
    name: 'Aprobar Pago de Préstamo',
    description: 'Validar y confirmar pago de préstamo.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:payments-loans',
    action: 'reject',
    name: 'Rechazar Pago de Préstamo',
    description: 'Rechazar o revertir pago de préstamo.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:payments-credits',
    action: 'create',
    name: 'Registrar Pago de Crédito',
    description: 'Cargar pago/abono a cuota de crédito.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:payments-credits',
    action: 'read',
    name: 'Consultar Pagos de Crédito',
    description: 'Ver historial de pagos de créditos.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:payments-credits',
    action: 'approve',
    name: 'Aprobar Pago de Crédito',
    description: 'Validar y confirmar pago de crédito.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:payments-credits',
    action: 'reject',
    name: 'Rechazar Pago de Crédito',
    description: 'Rechazar o revertir pago de crédito.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:products',
    action: 'create',
    name: 'Crear Producto Financiero',
    description: 'Configurar productos financieros.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:products',
    action: 'read',
    name: 'Consultar Productos',
    description: 'Ver productos financieros disponibles.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:products',
    action: 'update',
    name: 'Editar Producto',
    description: 'Modificar configuración de producto.',
    scope: 'tenant',
  },
  {
    resource: 'portfolio:products',
    action: 'delete',
    name: 'Eliminar Producto',
    description: 'Eliminar producto financiero.',
    scope: 'tenant',
  },

  // ==========================================
  // MODULO: ACCOUNTING (Contabilidad)
  // ==========================================
  {
    resource: 'accounting:chart_of_accounts',
    action: 'create',
    name: 'Crear Cuenta Contable',
    description: 'Agregar cuentas al plan de cuentas.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:chart_of_accounts',
    action: 'read',
    name: 'Consultar Plan de Cuentas',
    description: 'Ver estructura contable y saldos.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:chart_of_accounts',
    action: 'update',
    name: 'Editar Cuenta Contable',
    description: 'Modificar cuenta del plan de cuentas.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:chart_of_accounts',
    action: 'delete',
    name: 'Eliminar Cuenta Contable',
    description: 'Eliminar cuenta del plan de cuentas.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:rules',
    action: 'create',
    name: 'Crear Regla Contable',
    description: 'Configurar reglas de contabilización automática.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:rules',
    action: 'read',
    name: 'Consultar Reglas Contables',
    description: 'Ver reglas de contabilización.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:rules',
    action: 'update',
    name: 'Editar Regla Contable',
    description: 'Modificar regla de contabilización.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:rules',
    action: 'delete',
    name: 'Eliminar Regla Contable',
    description: 'Eliminar regla de contabilización.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:journal_entries',
    action: 'create',
    name: 'Crear Asiento Contable',
    description: 'Registrar comprobante de diario.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:journal_entries',
    action: 'read',
    name: 'Consultar Asientos',
    description: 'Ver comprobantes de diario.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:journal_entries',
    action: 'update',
    name: 'Editar Asiento',
    description: 'Modificar asiento en estado borrador.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:journal_entries',
    action: 'approve',
    name: 'Postear Asiento',
    description: 'Aprobar/contabilizar asiento definitivo.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:journal_entries',
    action: 'reject',
    name: 'Rechazar Asiento',
    description: 'Rechazar o anular asiento contable.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:cycles',
    action: 'create',
    name: 'Abrir Ciclo Contable',
    description: 'Iniciar nuevo período contable.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:cycles',
    action: 'read',
    name: 'Consultar Ciclos',
    description: 'Ver ciclos contables.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:cycles',
    action: 'update',
    name: 'Editar Ciclo Contable',
    description: 'Modificar datos del ciclo.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:cycles',
    action: 'delete',
    name: 'Cancelar Ciclo',
    description: 'Cancelar o anular ciclo contable.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:cycles',
    action: 'process',
    name: 'Cerrar Ciclo',
    description: 'Ejecutar cierre contable mensual/anual.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:reports',
    action: 'read',
    name: 'Generar Estados Financieros',
    description: 'Emitir Balance General, Edo. Resultados y libros.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:reports',
    action: 'execute',
    name: 'Exportar Reportes',
    description: 'Exportar reportes contables a PDF/Excel.',
    scope: 'tenant',
  },
  {
    resource: 'accounting:balances',
    action: 'read',
    name: 'Consultar Saldos',
    description: 'Ver saldos de cuentas contables.',
    scope: 'tenant',
  },

  // ==========================================
  // MODULO: BANKING (Bancos y Tesorería)
  // ==========================================
  {
    resource: 'banking:directory',
    action: 'read',
    name: 'Consultar Directorio Bancos',
    description: 'Ver catálogo de bancos del sistema.',
    scope: 'global',
  },
  {
    resource: 'banking:accounts',
    action: 'create',
    name: 'Registrar Cuenta Bancaria',
    description: 'Configurar cuentas bancarias del tenant.',
    scope: 'tenant',
  },
  {
    resource: 'banking:accounts',
    action: 'read',
    name: 'Consultar Cuentas Bancarias',
    description: 'Ver cuentas bancarias del tenant.',
    scope: 'tenant',
  },
  {
    resource: 'banking:accounts',
    action: 'update',
    name: 'Editar Cuenta Bancaria',
    description: 'Modificar datos de cuenta bancaria.',
    scope: 'tenant',
  },
  {
    resource: 'banking:accounts',
    action: 'delete',
    name: 'Desactivar Cuenta Bancaria',
    description: 'Desactivar cuenta bancaria.',
    scope: 'tenant',
  },
  {
    resource: 'banking:transactions',
    action: 'create',
    name: 'Registrar Transacción Bancaria',
    description: 'Registrar movimientos bancarios manuales.',
    scope: 'tenant',
  },
  {
    resource: 'banking:transactions',
    action: 'read',
    name: 'Consultar Transacciones',
    description: 'Ver movimientos bancarios.',
    scope: 'tenant',
  },
  {
    resource: 'banking:transactions',
    action: 'update',
    name: 'Editar Transacción',
    description: 'Modificar transacción bancaria.',
    scope: 'tenant',
  },
  {
    resource: 'banking:transactions',
    action: 'approve',
    name: 'Aprobar Transacción',
    description: 'Validar y confirmar transacción bancaria.',
    scope: 'tenant',
  },
  {
    resource: 'banking:reconciliation',
    action: 'read',
    name: 'Consultar Conciliaciones',
    description: 'Ver procesos de conciliación.',
    scope: 'tenant',
  },
  {
    resource: 'banking:reconciliation',
    action: 'process',
    name: 'Ejecutar Conciliación',
    description: 'Ejecutar conciliación bancaria.',
    scope: 'tenant',
  },
  {
    resource: 'banking:reconciliation',
    action: 'approve',
    name: 'Aprobar Conciliación',
    description: 'Validar y cerrar conciliación.',
    scope: 'tenant',
  },

  // ==========================================
  // MODULO: INVENTORY (Inventario)
  // ==========================================
  {
    resource: 'inventory:categories',
    action: 'create',
    name: 'Crear Categoria',
    description: 'Registrar nueva categoria en catálogo.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:categories',
    action: 'read',
    name: 'Consultar Categorias',
    description: 'Ver catálogo de categorias.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:categories',
    action: 'update',
    name: 'Editar Categoria',
    description: 'Modificar datos de la categoria.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:categories',
    action: 'delete',
    name: 'Desactivar Categoria',
    description: 'Desactivar categoria del catálogo.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:products',
    action: 'create',
    name: 'Crear Producto',
    description: 'Registrar nuevo producto en catálogo.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:products',
    action: 'read',
    name: 'Consultar Productos',
    description: 'Ver catálogo de productos.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:products',
    action: 'update',
    name: 'Editar Producto',
    description: 'Modificar datos del producto.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:products',
    action: 'delete',
    name: 'Desactivar Producto',
    description: 'Desactivar producto del catálogo.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:services',
    action: 'create',
    name: 'Crear Servicio',
    description: 'Registrar nuevo servicio en catálogo.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:services',
    action: 'read',
    name: 'Consultar Servicios',
    description: 'Ver catálogo de servicios.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:services',
    action: 'update',
    name: 'Editar Servicio',
    description: 'Modificar datos del servicio.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:services',
    action: 'delete',
    name: 'Desactivar Servicio',
    description: 'Desactivar servicio del catálogo.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:assets',
    action: 'create',
    name: 'Registrar Activo Fijo',
    description: 'Dar de alta un activo fijo.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:assets',
    action: 'read',
    name: 'Consultar Activos Fijos',
    description: 'Ver registro de activos fijos.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:assets',
    action: 'update',
    name: 'Editar Activo Fijo',
    description: 'Modificar datos del activo fijo.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:assets',
    action: 'delete',
    name: 'Desincorporar Activo Fijo',
    description: 'Dar de baja un activo fijo.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:stock',
    action: 'read',
    name: 'Consultar Stock',
    description: 'Ver niveles de inventario.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:stock',
    action: 'update',
    name: 'Ajustar Stock',
    description: 'Realizar ajustes de inventario.',
    scope: 'tenant',
  },
  {
    resource: 'inventory:stock',
    action: 'process',
    name: 'Procesar Movimientos',
    description: 'Ejecutar movimientos de entrada/salida.',
    scope: 'tenant',
  },

  // ==========================================
  // MODULO: PURCHASING (Compras)
  // ==========================================
  {
    resource: 'purchasing:orders',
    action: 'create',
    name: 'Crear Orden de Compra',
    description: 'Registrar nueva orden de compra.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:orders',
    action: 'read',
    name: 'Consultar Órdenes',
    description: 'Ver órdenes de compra.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:orders',
    action: 'update',
    name: 'Editar Orden',
    description: 'Modificar orden de compra.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:orders',
    action: 'delete',
    name: 'Cancelar Orden',
    description: 'Cancelar orden de compra.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:orders',
    action: 'approve',
    name: 'Aprobar Orden',
    description: 'Aprobar orden de compra.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:orders',
    action: 'receive',
    name: 'Recibir Orden',
    description: 'Registrar recepción de mercancía.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:providers',
    action: 'create',
    name: 'Registrar Proveedor',
    description: 'Dar de alta un nuevo proveedor.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:providers',
    action: 'read',
    name: 'Consultar Proveedores',
    description: 'Ver catálogo de proveedores.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:providers',
    action: 'update',
    name: 'Editar Proveedor',
    description: 'Modificar datos del proveedor.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:providers',
    action: 'delete',
    name: 'Desactivar Proveedor',
    description: 'Desactivar proveedor.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:invoices',
    action: 'create',
    name: 'Registrar Factura',
    description: 'Registrar factura de proveedor.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:invoices',
    action: 'read',
    name: 'Consultar Facturas',
    description: 'Ver facturas de proveedores.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:invoices',
    action: 'update',
    name: 'Editar Factura',
    description: 'Modificar factura de proveedor.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:invoices',
    action: 'delete',
    name: 'Anular Factura',
    description: 'Anular factura de proveedor.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:invoices',
    action: 'approve',
    name: 'Aprobar Factura',
    description: 'Validar y contabilizar factura.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:invoices',
    action: 'process',
    name: 'Contabilizar Factura',
    description: 'Ejecutar contabilización automática.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:payments',
    action: 'create',
    name: 'Registrar Pago',
    description: 'Crear orden de pago a proveedor.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:payments',
    action: 'read',
    name: 'Consultar Pagos',
    description: 'Ver pagos a proveedores.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:payments',
    action: 'update',
    name: 'Editar Pago',
    description: 'Modificar orden de pago.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:payments',
    action: 'approve',
    name: 'Aprobar Pago',
    description: 'Validar orden de pago.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:payments',
    action: 'disburse',
    name: 'Desembolsar Pago',
    description: 'Ejecutar el pago al proveedor.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:payments',
    action: 'process',
    name: 'Procesar Lote de Pagos',
    description: 'Procesar pagos en lote.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:reports',
    action: 'read',
    name: 'Consultar Reportes',
    description: 'Ver reportes de compras.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:reports',
    action: 'execute',
    name: 'Exportar Reportes Compras',
    description: 'Exportar reportes de compras.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:accounts_payable',
    action: 'read',
    name: 'Consultar CxP',
    description: 'Ver cuentas por pagar.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:accounts_payable',
    action: 'update',
    name: 'Editar CxP',
    description: 'Modificar estado de cuentas por pagar.',
    scope: 'tenant',
  },
  {
    resource: 'purchasing:accounts_payable',
    action: 'process',
    name: 'Procesar CxP',
    description: 'Ejecutar procesos de cuentas por pagar.',
    scope: 'tenant',
  },

  // ==========================================
  // MODULO: CATALOG (Catálogos Globales)
  // ==========================================
  {
    resource: 'catalog:currencies',
    action: 'read',
    name: 'Consultar Monedas',
    description: 'Ver monedas del sistema.',
    scope: 'global',
  },
  {
    resource: 'catalog:exchange_rates',
    action: 'read',
    name: 'Consultar Tasas de Cambio',
    description: 'Ver histórico de tasas de cambio.',
    scope: 'global',
  },
  {
    resource: 'catalog:exchange_rates',
    action: 'update',
    name: 'Actualizar Tasas',
    description: 'Modificar tasas de cambio (manual/automático).',
    scope: 'global',
  },
  {
    resource: 'catalog:categories',
    action: 'create',
    name: 'Crear Categoría',
    description: 'Configurar categorías locales del tenant.',
    scope: 'tenant',
  },
  {
    resource: 'catalog:categories',
    action: 'read',
    name: 'Consultar Categorías',
    description: 'Ver categorías registradas.',
    scope: 'tenant',
  },
  {
    resource: 'catalog:categories',
    action: 'update',
    name: 'Editar Categoría',
    description: 'Modificar categoría existente.',
    scope: 'tenant',
  },
  {
    resource: 'catalog:categories',
    action: 'delete',
    name: 'Eliminar Categoría',
    description: 'Eliminar categoría.',
    scope: 'tenant',
  },
  {
    resource: 'catalog:geography',
    action: 'read',
    name: 'Consultar Geografía',
    description: 'Ver catálogo de estados/municipios/parroquias.',
    scope: 'global',
  },
] as const;
