export const ACCOUNT_PAYABLE_STATUS_TYPES = {
  PENDING: 'PENDIENTE',
  PAID: 'PAGADA',
  IN_PROGRESS: 'PARCIALMENTE PAGADA',
  EXPIRED: 'VENCIDA',
  CANCELLED: 'CANCELADA',
  ADVANCE: 'AVANCE',
} as const;

export type AccountPayableStatusType =
  keyof typeof ACCOUNT_PAYABLE_STATUS_TYPES;

export enum AccountPayableStatusEnum {
  PENDING = 'PENDING',
  PAID = 'PAID',
  IN_PROGRESS = 'IN_PROGRESS',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  ADVANCE = 'ADVANCE',
}
