export const PAYMENT_METHOD = {
  CASH: 'CASH',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CHECK: 'CHECK',
  DEPOSIT: 'DEPOSIT',
  MOBILE_PAYMENT: 'MOBILE_PAYMENT',
  OTHER: 'OTHER',
} as const;

export type PaymentMethod = (typeof PAYMENT_METHOD)[keyof typeof PAYMENT_METHOD];

export const PAYMENT_METHOD_OPTIONS = {
  [PAYMENT_METHOD.CASH]: 'Efectivo',
  [PAYMENT_METHOD.BANK_TRANSFER]: 'Transferencia',
  [PAYMENT_METHOD.CHECK]: 'Cheque',
  [PAYMENT_METHOD.DEPOSIT]: 'Depósito',
  [PAYMENT_METHOD.MOBILE_PAYMENT]: 'Pago Móvil',
  [PAYMENT_METHOD.OTHER]: 'Otro',
} as const;

export const CATEGORY = {
  MEMBER_CONTRIBUTION: 'MEMBER_CONTRIBUTION',
  MEMBER_WITHDRAWAL: 'MEMBER_WITHDRAWAL',
  PAYROLL_SETTLEMENT: 'PAYROLL_SETTLEMENT',
  LOAN_DISBURSEMENT: 'LOAN_DISBURSEMENT',
  LOAN_PAYMENT: 'LOAN_PAYMENT',
  CREDIT_DISBURSEMENT: 'CREDIT_DISBURSEMENT',
  CREDIT_PAYMENT: 'CREDIT_PAYMENT',
  BATCH_DISBURSEMENT: 'BATCH_DISBURSEMENT',
  SUPPLIER_PAYMENT: 'SUPPLIER_PAYMENT',
  SUPPLIER_ADVANCE_PAYMENT: 'SUPPLIER_ADVANCE_PAYMENT',
} as const;

export type Category = (typeof CATEGORY)[keyof typeof CATEGORY];

export const CATEGORY_OPTIONS = {
  [CATEGORY.MEMBER_CONTRIBUTION]: 'Aporte Socio',
  [CATEGORY.MEMBER_WITHDRAWAL]: 'Retiro Socio',
  [CATEGORY.PAYROLL_SETTLEMENT]: 'Liquidación',
  [CATEGORY.LOAN_DISBURSEMENT]: 'Desembolso Préstamo',
  [CATEGORY.LOAN_PAYMENT]: 'Pago Préstamo',
  [CATEGORY.CREDIT_DISBURSEMENT]: 'Desembolso Crédito',
  [CATEGORY.CREDIT_PAYMENT]: 'Pago Crédito',
  [CATEGORY.BATCH_DISBURSEMENT]: 'Desembolso por Lote',
  [CATEGORY.SUPPLIER_PAYMENT]: 'Pago a Proveedor',
  [CATEGORY.SUPPLIER_ADVANCE_PAYMENT]: 'Anticipo a Proveedor',
} as const;
