export const ACTION_OPTIONS = [
  { value: 'read', label: 'Leer' },
  { value: 'create', label: 'Crear' },
  { value: 'update', label: 'Actualizar' },
  { value: 'delete', label: 'Eliminar' },
  { value: 'execute', label: 'Ejecutar' },
  { value: 'approve', label: 'Aprobar' },
  { value: 'reject', label: 'Rechazar' },
  { value: 'process', label: 'Procesar' },
  { value: 'disburse', label: 'Desembolsar' },
  { value: 'mass_upload', label: 'Carga Masiva' },
  { value: 'mass_disburse', label: 'Desembolso Masivo' },
];

export const RESOURCE_OPTIONS = [
  { value: 'savings:members', label: 'Caja de Ahorro: Asociados' },
  { value: 'savings:contributions', label: 'Caja de Ahorro: Aportes' },
  { value: 'savings:withdrawals', label: 'Caja de Ahorro: Retiros' },
  {
    value: 'savings:withdrawal-types',
    label: 'Caja de Ahorro: Tipos de Retiros',
  },
  { value: 'savings:liquidations', label: 'Caja de Ahorro: Liquidaciones' },
  { value: 'savings:configuration', label: 'Caja de Ahorro: Configuración' },
  { value: 'portfolio:loans', label: 'Cartera: Préstamos' },
  { value: 'portfolio:loans-types', label: 'Cartera: Tipos de Préstamos' },
  { value: 'portfolio:credits', label: 'Cartera: Créditos' },
  { value: 'portfolio:credits-types', label: 'Cartera: Tipos de Créditos' },
  { value: 'portfolio:payments-loans', label: 'Cartera: Pagos de Préstamos' },
  { value: 'portfolio:payments-credits', label: 'Cartera: Pagos de Créditos' },
  { value: 'portfolio:payments', label: 'Cartera: Pagos' },
  { value: 'portfolio:products', label: 'Cartera: Productos' },
  {
    value: 'accounting:chart_of_accounts',
    label: 'Contabilidad: Plan de Cuentas',
  },
  { value: 'accounting:rules', label: 'Contabilidad: Reglas' },
  { value: 'accounting:journal_entries', label: 'Contabilidad: Asientos' },
  { value: 'accounting:reports', label: 'Contabilidad: Reportes' },
  { value: 'accounting:cycles', label: 'Contabilidad: Ciclos' },
  { value: 'accounting:balances', label: 'Contabilidad: Balances' },
  { value: 'banking:directory', label: 'Banca: Directorio' },
  { value: 'banking:accounts', label: 'Banca: Cuentas' },
  { value: 'banking:transactions', label: 'Banca: Transacciones' },
  { value: 'banking:reconciliation', label: 'Banca: Conciliación' },
  { value: 'inventory:products', label: 'Inventario: Productos' },
  { value: 'inventory:services', label: 'Inventario: Servicios' },
  { value: 'inventory:assets', label: 'Inventario: Activos' },
  { value: 'inventory:stock', label: 'Inventario: Stock' },
  { value: 'purchasing:orders', label: 'Compras: Órdenes' },
  { value: 'purchasing:providers', label: 'Compras: Proveedores' },
  { value: 'purchasing:invoices', label: 'Compras: Facturas' },
  { value: 'purchasing:payments', label: 'Compras: Pagos' },
  { value: 'purchasing:reports', label: 'Compras: Reportes' },
  { value: 'purchasing:accounts_payable', label: 'Compras: Cuentas por Pagar' },
  { value: 'iam:users', label: 'IAM: Usuarios' },
  { value: 'iam:roles', label: 'IAM: Roles' },
  { value: 'iam:permissions', label: 'IAM: Permisos' },
  { value: 'iam:sessions', label: 'IAM: Sesiones' },
  { value: 'catalog:currencies', label: 'Catálogo: Monedas' },
  { value: 'catalog:exchange_rates', label: 'Catálogo: Tasas de Cambio' },
  { value: 'catalog:categories', label: 'Catálogo: Categorías' },
  { value: 'catalog:geography', label: 'Catálogo: Geografía' },
  { value: 'system:tenants', label: 'Sistema: Inquilinos' },
  { value: 'system:tenants-systems', label: 'Sistema: Sistemas de Inquilinos' },
  { value: 'system:global', label: 'Sistema: Global' },
  { value: 'system:currencies', label: 'Sistema: Monedas' },
  { value: 'system:modules', label: 'Sistema: Módulos' },
];

export const SCOPE_OPTIONS = [
  { value: 'own', label: 'Propio (Solo datos propios)' },
  { value: 'team', label: 'Equipo' },
  { value: 'department', label: 'Departamento/Área' },
  { value: 'branch', label: 'Sucursal' },
  { value: 'tenant', label: 'Inquilino (Tenant)' },
  { value: 'global', label: 'Global (Todos los datos)' },
  { value: 'all', label: 'Todo (Acceso total)' },
];
