export const ASSOCIATE_MOVEMENT_TYPES = {
  SAVING_CONTRIBUTION: 'APORTE ASOCIADO',
  EMPLOYER_CONTRIBUTION: 'APORTE EMPLEADOR',
  //DIVIDEND_CREDIT: 'CRÉDITO DIVIDENDO',
  //LOAN_DISBURSEMENT_CREDIT: 'CRÉDITO DESEMBOLSO PRÉSTAMO',
  //OTHER_CREDIT: 'OTRO CRÉDITO',
  //ADJUSTMENT_CREDIT: 'CRÉDITO AJUSTE',
  //FEE_REIMBURSEMENT_CREDIT: 'CRÉDITO REEMBOLSO TARIFAS',
} as const;

export type AssociateMovementType = keyof typeof ASSOCIATE_MOVEMENT_TYPES;
