import type { AccountEntry } from '../template.types';

export function computeParentCode(code: string): string | undefined {
  if (code.match(/^\d+\.\d{2}\.00\.00$/))
    return `${code.split('.')[0]}.00.00.00`;
  const s = code.split('.');
  if (code.match(/^\d+\.\d{2}\.\d{2}\.00$/)) return `${s[0]}.${s[1]}.00.00`;
  if (code.match(/^\d+\.\d{2}\.\d{2}\.\d{2}$/))
    return `${s[0]}.${s[1]}.${s[2]}.00`;
  if (code.match(/^\d+\.\d{2}\.\d{2}\.\d{2}\.\d{3}$/))
    return `${s[0]}.${s[1]}.${s[2]}.${s[3]}`;
  return undefined;
}

export const ACCOUNTS: AccountEntry[] = [
  {
    code: '100.00.00.00',
    name: 'ACTIVOS',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: undefined,
  },
  {
    code: '200.00.00.00',
    name: 'PASIVOS',
    accountType: 'LIABILITY',
    nature: 'CREDIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: undefined,
  },
  {
    code: '300.00.00.00',
    name: 'PATRIMONIO',
    accountType: 'EQUITY',
    nature: 'CREDIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: undefined,
  },
  {
    code: '400.00.00.00',
    name: 'INGRESOS',
    accountType: 'REVENUE',
    nature: 'CREDIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: undefined,
  },
  {
    code: '500.00.00.00',
    name: 'EGRESOS',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: undefined,
  },
  {
    code: '600.00.00.00',
    name: 'CUENTAS DE ORDEN DEUDORAS',
    accountType: 'MEMORANDUM',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: undefined,
  },
  {
    code: '700.00.00.00',
    name: 'CUENTAS DE ORDEN ACREEDORAS',
    accountType: 'MEMORANDUM',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: undefined,
  },
  {
    code: '110.00.00.00',
    name: 'DISPONIBILIDAD',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '100.00.00.00',
  },
  {
    code: '111.00.00.00',
    name: 'EFECTIVO',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '100.00.00.00',
  },
  {
    code: '112.00.00.00',
    name: 'BANCOS',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '100.00.00.00',
  },
  {
    code: '113.00.00.00',
    name: 'CUENTAS POR COBRAR',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '100.00.00.00',
  },
  {
    code: '114.00.00.00',
    name: 'INVENTARIOS',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '100.00.00.00',
  },
  {
    code: '115.00.00.00',
    name: 'ACTIVO CORRIENTE',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '100.00.00.00',
  },
  {
    code: '120.00.00.00',
    name: 'ACTIVO NO CORRIENTE',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '100.00.00.00',
  },
  {
    code: '121.00.00.00',
    name: 'PROPIEDAD PLANTA Y EQUIPO',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '100.00.00.00',
  },
  {
    code: '122.00.00.00',
    name: 'DEPRECIACION ACUMULADA',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '100.00.00.00',
  },
  {
    code: '130.00.00.00',
    name: 'OTROS ACTIVOS',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '100.00.00.00',
  },
  {
    code: '210.00.00.00',
    name: 'CUENTAS POR PAGAR',
    accountType: 'LIABILITY',
    nature: 'CREDIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '200.00.00.00',
  },
  {
    code: '211.00.00.00',
    name: 'OBLIGACIONES LABORALES',
    accountType: 'LIABILITY',
    nature: 'CREDIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '200.00.00.00',
  },
  {
    code: '212.00.00.00',
    name: 'IMPUESTOS POR PAGAR',
    accountType: 'LIABILITY',
    nature: 'CREDIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '200.00.00.00',
  },
  {
    code: '220.00.00.00',
    name: 'PASIVO NO CORRIENTE',
    accountType: 'LIABILITY',
    nature: 'CREDIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '200.00.00.00',
  },
  {
    code: '230.00.00.00',
    name: 'OTROS PASIVOS',
    accountType: 'LIABILITY',
    nature: 'CREDIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '200.00.00.00',
  },
  {
    code: '310.00.00.00',
    name: 'CAPITAL SOCIAL',
    accountType: 'EQUITY',
    nature: 'CREDIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '300.00.00.00',
  },
  {
    code: '320.00.00.00',
    name: 'RESERVAS',
    accountType: 'EQUITY',
    nature: 'CREDIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '300.00.00.00',
  },
  {
    code: '330.00.00.00',
    name: 'RESULTADOS ACUMULADOS',
    accountType: 'EQUITY',
    nature: 'CREDIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '300.00.00.00',
  },
  {
    code: '410.00.00.00',
    name: 'INGRESOS OPERACIONALES',
    accountType: 'REVENUE',
    nature: 'CREDIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '400.00.00.00',
  },
  {
    code: '420.00.00.00',
    name: 'INGRESOS NO OPERACIONALES',
    accountType: 'REVENUE',
    nature: 'CREDIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '400.00.00.00',
  },
  {
    code: '510.00.00.00',
    name: 'COSTO DE VENTAS',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '500.00.00.00',
  },
  {
    code: '511.00.00.00',
    name: 'GASTOS OPERACIONALES',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '500.00.00.00',
  },
  {
    code: '512.00.00.00',
    name: 'GASTOS ADMINISTRATIVOS',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '500.00.00.00',
  },
  {
    code: '513.00.00.00',
    name: 'GASTOS DE VENTAS',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '500.00.00.00',
  },
  {
    code: '520.00.00.00',
    name: 'GASTOS NO OPERACIONALES',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '500.00.00.00',
  },
  {
    code: '610.00.00.00',
    name: 'CUENTAS DE ORDEN DEUDORAS',
    accountType: 'MEMORANDUM',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '600.00.00.00',
  },
  {
    code: '710.00.00.00',
    name: 'CUENTAS DE ORDEN ACREEDORAS',
    accountType: 'MEMORANDUM',
    nature: 'DEBIT',
    level: 1,
    allowsMovements: false,
    isActive: true,
    parentCode: '700.00.00.00',
  },
  {
    code: '110.01.00.00',
    name: 'Caja General',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '110.00.00.00',
  },
  {
    code: '110.02.00.00',
    name: 'Caja Chica',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '110.00.00.00',
  },
  {
    code: '111.01.00.00',
    name: 'Efectivo en Bancos',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '111.00.00.00',
  },
  {
    code: '112.01.00.00',
    name: 'Banco Union',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '112.00.00.00',
  },
  {
    code: '112.02.00.00',
    name: 'Banco Mercantil',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '112.00.00.00',
  },
  {
    code: '112.03.00.00',
    name: 'Banco Bisa',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '112.00.00.00',
  },
  {
    code: '113.01.00.00',
    name: 'Clientes',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '113.00.00.00',
  },
  {
    code: '113.02.00.00',
    name: 'Deudores Varios',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '113.00.00.00',
  },
  {
    code: '113.03.00.00',
    name: 'Anticipos a Proveedores',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '113.00.00.00',
  },
  {
    code: '114.01.00.00',
    name: 'Inventario de Mercancias',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '114.00.00.00',
  },
  {
    code: '114.02.00.00',
    name: 'Inventario de Materia Prima',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '114.00.00.00',
  },
  {
    code: '121.01.00.00',
    name: 'Terrenos',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '121.00.00.00',
  },
  {
    code: '121.02.00.00',
    name: 'Edificios',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '121.00.00.00',
  },
  {
    code: '121.03.00.00',
    name: 'Mobiliario y Equipo',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '121.00.00.00',
  },
  {
    code: '121.04.00.00',
    name: 'Equipo de Computacion',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '121.00.00.00',
  },
  {
    code: '121.05.00.00',
    name: 'Vehiculos',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '121.00.00.00',
  },
  {
    code: '122.01.00.00',
    name: 'Depreciacion Acumulada Edificios',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '122.00.00.00',
  },
  {
    code: '122.02.00.00',
    name: 'Depreciacion Acumulada Mobiliario',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '122.00.00.00',
  },
  {
    code: '122.03.00.00',
    name: 'Depreciacion Acumulada Vehiculos',
    accountType: 'ASSET',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '122.00.00.00',
  },
  {
    code: '210.01.00.00',
    name: 'Proveedores',
    accountType: 'LIABILITY',
    nature: 'CREDIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '210.00.00.00',
  },
  {
    code: '210.02.00.00',
    name: 'Acreedores Varios',
    accountType: 'LIABILITY',
    nature: 'CREDIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '210.00.00.00',
  },
  {
    code: '211.01.00.00',
    name: 'Sueldos por Pagar',
    accountType: 'LIABILITY',
    nature: 'CREDIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '211.00.00.00',
  },
  {
    code: '211.02.00.00',
    name: 'Beneficios Sociales por Pagar',
    accountType: 'LIABILITY',
    nature: 'CREDIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '211.00.00.00',
  },
  {
    code: '212.01.00.00',
    name: 'IVA por Pagar',
    accountType: 'LIABILITY',
    nature: 'CREDIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '212.00.00.00',
  },
  {
    code: '212.02.00.00',
    name: 'IT por Pagar',
    accountType: 'LIABILITY',
    nature: 'CREDIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '212.00.00.00',
  },
  {
    code: '212.03.00.00',
    name: 'IUE por Pagar',
    accountType: 'LIABILITY',
    nature: 'CREDIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '212.00.00.00',
  },
  {
    code: '310.01.00.00',
    name: 'Capital Suscrito',
    accountType: 'EQUITY',
    nature: 'CREDIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '310.00.00.00',
  },
  {
    code: '310.02.00.00',
    name: 'Aportes de Socios',
    accountType: 'EQUITY',
    nature: 'CREDIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '310.00.00.00',
  },
  {
    code: '320.01.00.00',
    name: 'Reserva Legal',
    accountType: 'EQUITY',
    nature: 'CREDIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '320.00.00.00',
  },
  {
    code: '330.01.00.00',
    name: 'Utilidades Retenidas',
    accountType: 'EQUITY',
    nature: 'CREDIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '330.00.00.00',
  },
  {
    code: '410.01.00.00',
    name: 'Ventas de Mercancias',
    accountType: 'REVENUE',
    nature: 'CREDIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '410.00.00.00',
  },
  {
    code: '410.02.00.00',
    name: 'Ventas de Productos',
    accountType: 'REVENUE',
    nature: 'CREDIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '410.00.00.00',
  },
  {
    code: '410.03.00.00',
    name: 'Descuentos en Ventas',
    accountType: 'REVENUE',
    nature: 'CREDIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '410.00.00.00',
  },
  {
    code: '420.01.00.00',
    name: 'Ingresos Financieros',
    accountType: 'REVENUE',
    nature: 'CREDIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '420.00.00.00',
  },
  {
    code: '420.02.00.00',
    name: 'Otros Ingresos',
    accountType: 'REVENUE',
    nature: 'CREDIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '420.00.00.00',
  },
  {
    code: '510.01.00.00',
    name: 'Costo de Ventas',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '510.00.00.00',
  },
  {
    code: '511.01.00.00',
    name: 'Sueldos y Salarios',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '511.00.00.00',
  },
  {
    code: '511.02.00.00',
    name: 'Cargas Sociales',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '511.00.00.00',
  },
  {
    code: '511.03.00.00',
    name: 'Honorarios Profesionales',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '511.00.00.00',
  },
  {
    code: '512.01.00.00',
    name: 'Servicios Basicos',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '512.00.00.00',
  },
  {
    code: '512.02.00.00',
    name: 'Alquileres',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '512.00.00.00',
  },
  {
    code: '512.03.00.00',
    name: 'Mantenimiento',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '512.00.00.00',
  },
  {
    code: '512.04.00.00',
    name: 'Utiles de Oficina',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '512.00.00.00',
  },
  {
    code: '513.01.00.00',
    name: 'Publicidad',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '513.00.00.00',
  },
  {
    code: '513.02.00.00',
    name: 'Comisiones sobre Ventas',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '513.00.00.00',
  },
  {
    code: '520.01.00.00',
    name: 'Gastos Financieros',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '520.00.00.00',
  },
  {
    code: '520.02.00.00',
    name: 'Perdida en Venta de Activos',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '520.00.00.00',
  },
  {
    code: '510.02.00.00',
    name: 'Depreciacion',
    accountType: 'EXPENSE',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '510.00.00.00',
  },
  {
    code: '610.01.00.00',
    name: 'Garantias Recibidas',
    accountType: 'MEMORANDUM',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '610.00.00.00',
  },
  {
    code: '710.01.00.00',
    name: 'Garantias Recibidas',
    accountType: 'MEMORANDUM',
    nature: 'DEBIT',
    level: 2,
    allowsMovements: true,
    isActive: true,
    parentCode: '710.00.00.00',
  },
];
